[theme]
base = "light"
primaryColor = "#1976d2"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

[server]
runOnSave = true
port = 8510

[browser]
gatherUsageStats = false
